### ISSUE TITLE
Chars wrapper around Bytes

### ISSUE THREAD

**Issue by stepancheg** [carllerche/bytes#105]
Would be convenient if `bytes` trait had a thin `Chars` wrapper around `Bytes`.

`Chars` should be identical to `Bytes` except it should guarantee that it always contains valid UTF-8 sequence.

`Chars` to `Bytes` is the same as `String` to `Vec<u8>`.

**Comment by carllerche** [comment]
I personally lean towards having something like `Chars`... it would be nice to have. That said, I'll leave this issue open so that hopefully others can weigh in. My personal opinion isn't strong either way on this issue.

cc/ @alexcrichton

**Comment by alexcrichton** [comment]
Given the name of the crate, "bytes", and the number of dependencies on this crate I'd be tempted to keep it lean and move the utf-8 support to an external crate.

**Comment by carllerche** [comment]
Given how small a `Chars` wrapper would be, I think for now it would be wise to keep it out of the bytes crate until a compelling use case is determined. I'm going to close the issue for now.

**Comment by carllerche** [comment]
FYI, I made a wrapper here: github.com/carllerche/string
