### ISSUE TITLE
BytesMut::reserve not working for most values.

### ISSUE THREAD

**Issue by xalri** [carllerche/bytes#113]
It's possible I'm missunderstanding something, but this seems to be a bug: most calls to `bytes.reserve(a)` on a buffer with capacity `b` result in the buffer having a capacity smaller than `a + b`.

```rust
extern crate bytes;
use bytes::*;

#[test]
fn bytes_reserve() {
   let mut bytes = BytesMut::with_capacity(20);
   bytes.reserve(12);
   bytes.put(vec![0; 32]);

   let mut bytes = BytesMut::with_capacity(20);
   bytes.reserve(44);
   bytes.put(vec![0; 64]);
}
```

Both calls to `bytes.put` panic:
```
thread 'bytes_reserve' panicked at 'assertion failed: self.remaining_mut() >= src.remaining()', /home/xal/.cargo/git/checkouts/bytes-72cf269819849e12/37f6cab/src/buf/buf_mut.rs:229```

**Comment by carllerche** [comment]
Thanks for the issue report. `BytesMut::reserve` doesn't add `n` more bytes of capacity. It guarantees that a write of `n` bytes will succeed. In the example, you reserve less than the next write, in which case the write is not guaranteed to succeed.

If you think the docs are unclear, could you clarify what in the docs makes you think that your code snippet should work?

**Comment by xalri** [comment]
Ah, I see now ^^
> Reserves capacity for at least additional more bytes to be _inserted_ into the given BytesMut.

Yeah, I can't think of how the docs could be changed such that I wouldn't have mis-understood -- it's clear in hindsight.
Thanks for the quick response :)
