### ISSUE TITLE
Implement ExactSizeIterator for Iter<T: Buf>

### ISSUE THREAD

**Issue by brianwp** [carllerche/bytes#126]
An std::iter::[ExactSizeIterator](https://doc.rust-lang.org/std/iter/trait.ExactSizeIterator.html) is "an iterator that knows its exact length". 
Implementing ExactSizeIterator for Iter<T: Buf> is trivial because it already returns the exact size in its implementation of size_hint()--it just needs an empty trait impl.

**Comment by carllerche** [comment]
Fixed by #127
