### ISSUE TITLE
Inconsistency between BytesMut and Vec impl of BufMut

### ISSUE THREAD

**Issue by stepancheg** [carllerche/bytes#131]
This code works:

```
    let mut buf = Vec::new();

    for _ in 0..1000 {
        buf.put_u8(1);
    }
```

This code crashes:

```
    let mut buf = BytesMut::new();

    for _ in 0..1000 {
        buf.put_u8(1);
    }
```

I think behavior should be similar because of least surprise principle.

(Probably, `BytesMut` should implicitly reserve).

**Comment by carllerche** [comment]
My original thought was that I didn't want buffers to implicitly grow. I think this is a common case in networking scenarios. I often have code that fill as much of the buffer as possible then write flush, then fill more. This specifically shows up in how BufMut is implemented. Code that is generic over BufMut look at the remaining argument and if the buffer implicitly grows then the return value of remaining is usize::MAX. 

That said, I understand that the inconsistency is not great and could be convinced to switch.

This change would be a breaking change I believe. I know that I would have a bunch of code that semantically breaks. 

Cc @alexcrichton

**Comment by alexcrichton** [comment]
I agree these should be consistent. If we change the behavior of `Vec` I'd consider it a breaking change, and if we changed the behavior of `BytesMut` I would not personally at least consider it a breaking change.

I would personally advocate for `Vec`'s strategy.

**Comment by carllerche** [comment]
@alexcrichton implementing this change in BytesMut would expose any existing code using BytesMut to DOS attacks... sounds like a breaking change to me :)

**Comment by cramertj** [comment]
I'm confused-- if your usages always reserve the necessary space and then fill the buffer, why would changing the buffer to autofill if you didn't reserve the necessary space be a breaking change? Do you have code that relies on BytesMut panicing in order to ensure correctness?

**Comment by carllerche** [comment]
@cramertj `put_u8` is a helper fn that is provided by `BufMut`. The breaking change is `BufMut::remaining_mut()`. To support this change, `BufMut::remaining_mut()` would have to return `usize::MAX` instead of the current remaining capacity.

Any code that relies on `remaining_mut` to return the remaining capacity would break.

**Comment by cramertj** [comment]
Why would you change the behavior of `remaining_mut`? It seems reasonable to leave it as a check on the remaining capacity, not the remaining possible size.

**Comment by carllerche** [comment]
`put_u8` depends on `remaining_mut` (it is a trait fn).

**Comment by carllerche** [comment]
Basically, this fn: https://github.com/carllerche/bytes/blob/master/src/buf/buf_mut.rs#L270-L293

**Comment by cramertj** [comment]
@carllerche Couldn't you change `put_slice` to expand the buffer instead of panicing? I don't see why that would be a breaking change unless someone was relying on the panic occurring.

**Comment by carllerche** [comment]
@cramertj the `remaining_mut` function behavior needs to change https://github.com/carllerche/bytes/blob/master/src/buf/buf_mut.rs#L273.

**Comment by cramertj** [comment]
Why does it need to change? `remaining_mut` could just refer to the remaining capacity without allocating rather than the remaining possible capacity. Then you can remove that assertion entirely, and replace it with an `ensure_capacity` call.

**Comment by carllerche** [comment]
Ah, I see, have `BytesMut` re-implement all of the fns w/o relying on `remaining_mut`.

I guess that could work... I'd have to consider it more.

**Comment by carllerche** [comment]
I'm closing this in favor of #170.
