### ISSUE TITLE
`Take<Chain< ... >>` panics when calling `bytes`.

### ISSUE THREAD

**Issue by ecstatic-morse** [carllerche/bytes#140]
This code will panic:

    let a = Cursor::new(Bytes::from(&b"hello"[..]));
    let b = Cursor::new(Bytes::from(&b"world"[..]));
    let mut out = vec![];
    out.put(a.chain(b).take(8));

with 

> index 8 out of range for slice of length 5

This is because `Take::bytes()` attempts to slice the result `Chain::bytes()` up to the minimum of the limit (8) and the number of bytes remaining in the `Chain` (10). However, `Chain::bytes()` returns only the first contiguous byte slice which has length 5.

*Edit:*
Actually `Buf::take()` always uses its limit parameter, not the minimum of the remaining bytes and the limit parameter as I initially thought. As a result, 

    let a = Cursor::new(Bytes::from(&b"hello"[..]));
    let mut out = vec![];
    out.put(a.take(8));

panics with the same message, which is, in my opinion, still a bit unintuitive but consistent with the behavior of the rest of the crate.

**Comment by danburkert** [comment]
This is #138.

**Comment by carllerche** [comment]
The fix was merged! Thanks.
