### ISSUE TITLE
bytes::buf::Chain::bytes() returns only first part

### ISSUE THREAD

**Issue by imp** [carllerche/bytes#152]
It seems that `bytes::buf::Chain::bytes()` does not behave correctly. As long as the first part of the chain has anything unconsumed it fails to take into account the other part of the chain.

Here is the test case that demonstrates the issue
```
#[test]
fn taking_bytes() {
    let a = Cursor::new(Bytes::from(&b"hello"[..]));
    let b = Cursor::new(Bytes::from(&b"world"[..]));

    let res = a.chain(b);
    assert_eq!(res.bytes(), &b"helloworld"[..]);
}
```

**Comment by danburkert** [comment]
This is by design.  Without performing an internal copy (which is avoided intentionally), it's impossible to implement `Chain` in a way that passes that test.  The current behavior is valid according to the documentation for `Buf::bytes`:

> Returns a slice starting at the current position and of length between 0 and Buf::remaining().

**Comment by imp** [comment]
Oh, I didn't realize that. I'd put an extra emphasize in the documentation on that fact so that that next potential consumer won't find it the hard way.
