### ISSUE TITLE
Implement From<Bytes> for Cow<'a, [u8]> for Bytes[Mut]

### ISSUE THREAD

**Issue by Thomasdezeeuw** [carllerche/bytes#157]
I'm currently working with a [`Cow`](https://doc.rust-lang.org/nightly/std/borrow/enum.Cow.html) type, and it would be nice if I could use `Bytes` to created an owned version of the `Cow` type. I believe this would also require [`ToOwned`](https://doc.rust-lang.org/nightly/std/borrow/trait.ToOwned.html) to be implemented.

Would such a change be accepted?

**Comment by carllerche** [comment]
Hey there. Could you elaborate more on how you would like to see `Bytes` and `Cow` work together? It doesn't seem like there would be much win?

**Comment by Thomasdezeeuw** [comment]
Basically I have a type which can be parsed from raw bytes. For performance reason I'm borrowing some of those bytes in the structure, rather then copying them. I'm using tokio-io's `Framer`, which requires the `Decoder` and `Encoder` traits, both of which use `Bytes[Mut]` in the `decode`/`encode` functions.

Now in case of `decode` I need to take ownership of the bytes, because if I only borrow them they will get dropped at the end of the function and Rust (correctly) won't allow this. So I decided to use a `Cow` to indicate wether or not the bytes are owned or borrowed, the bytes are never mutated so it's really only to please the borrow checker.

Hopefully the code below will illustrate my problem.

```rust
struct Frame<'a> {
    data: Cow<'a, [u8]>,
}

impl<'a> Frame<'a> {
    fn from_bytes(bytes: &'a [u8]) -> Frame<'a> {
        Frame {
            data: Cow::from(bytes),
        }
    }

    fn from_owned_bytes(bytes: Bytes) -> Frame<'a> {
        Frame {
            // Currently not possible, but I would like it to be.
            data: Cow::from(bytes),
        }
    }
}

fn decode(&mut self, src: &mut BytesMut) -> io::Result<Option<Self::Item>> {
    // Doesn't work but it's the basic code.
    let frame_bytes = src.split_off(size).freeze();
    Frame::from_owned_bytes(frame_bytes)
}
```

**Comment by carllerche** [comment]
I don't think that is possible to do.`ToOwned` has the target type set as an associated type. So, `[u8]` will always convert to `Vec<u8>`.

That said, you can convert a `Vec<u8>` -> `Bytes` w/o any overhead, so it is just an extra conversion call.

**Comment by Thomasdezeeuw** [comment]
But not the other way around, I need to store `Bytes` (or a type into which `Bytes` can cheaply be converted into) and only need a reference to a byte slice (`[u8]`). I never mutate the bytes stored in `Frame`.

I'll try to code something tommorow and report back ok?

**Comment by Thomasdezeeuw** [comment]
Unfortunately I think you're right and you can't implement `ToOwned` for `[u8]` using `Bytes`. This can be closed then.
