### ISSUE TITLE
Is it safe to use  size_hint() in Extend implementation?

### ISSUE THREAD

**Issue by glebpom** [carllerche/bytes#159]
Hello,

According to Rust [std lib documentation](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint), `size_hint` should not be treated as reliable, hence should not be trusted. 
It seems like `Extend` implementation trusts the `size_hint`. Is it safe enough?

**Comment by carllerche** [comment]
Sorry, could you provide more info? I'm not understanding this issue.

**Comment by glebpom** [comment]
Here is the code from `https://github.com/carllerche/bytes/blob/master/src/bytes.rs`
```
impl Extend<u8> for BytesMut {
    fn extend<T>(&mut self, iter: T) where T: IntoIterator<Item = u8> {
        let iter = iter.into_iter();

        let (lower, _) = iter.size_hint();
        self.reserve(lower);

        for b in iter {
            unsafe {
                self.bytes_mut()[0] = b;
                self.advance_mut(1);
            }
        }
    }
}
```

As far as I understand, it reserves additional space for `self` according to the lower bound returned from the `size_hint`. If `size_hint` information is incorrect (which is described in the rust std lib documentation), it may lead to panic in `advance_mut`

**Comment by carllerche** [comment]
Ah yes, this is possible. Are you able to provide a fix + test?

**Comment by glebpom** [comment]
The first idea which comes to my mind is to use `count()` on cloned `Iterator`. The drawback of this solution is that it may be less efficient. BTW, does it make sense to always reserve additional space, even if there is enough available?

**Comment by carllerche** [comment]
We probably shouldn't use `count` as that iterates the iterator. I would say that we should:

* Call `reserve(lower)` initially.
* Call `reserve(1)` each iteration.

`reserve` should be fast enough and not allocate if unneeded. Any fancier logic should be benchmark / profile driven.

**Comment by cramertj** [comment]
I don't think this needs to be changed so long as `advance_mut` will panic rather than trying to write past the end of the buffer. Panicing on incorrect `size_hint` is just fine-- it doesn't cause memory unsafety.
From the docs of `size_hint`:

> An incorrect implementation of size_hint() should not lead to memory safety violations.
That said, the implementation should provide a correct estimation, because otherwise it would be a violation of the trait's protocol.

**Comment by carllerche** [comment]
If that is true, then `bytes_mut` and `advance_mut` are definitely required to ensure memory safety.

I'll close this issue.
