### ISSUE TITLE
IoVec::default test failures

### ISSUE THREAD

**Issue by mspiegel** [carllerche/bytes#160]
When I try to run tests I get the message 'this implementation was accidentally provided but is unfortunately unsound, it's recommended to stop using `IoVec::default` or construct a vector with a nonzero length'. I think it's related to https://github.com/carllerche/iovec/commit/007031f4b4f7f518ea6b1888b0bc189604430dbd. My rustfoo is not strong enough. Is there something I should do as a workaround?

**Comment by carllerche** [comment]
Thanks for the report. I fixed this on master :) 149922d7cf4b76d00066bb8615df2f7b1d9ace44
