### ISSUE TITLE
Object safety for traits

### ISSUE THREAD

**Issue by tailhook** [carllerche/bytes#163]
Currently, rust complains:
```
error[E0038]: the trait `bytes::Buf` cannot be made into an object
  --> src/proto.rs:17:5
   |
17 |     buf: Option<Box<Buf>>,
   |     ^^^^^^^^^^^^^^^^^^^^^ the trait `bytes::Buf` cannot be made into an object
   |
   = note: method `get_u16` has generic type parameters
   = note: method `get_i16` has generic type parameters
   = note: method `get_u32` has generic type parameters
   = note: method `get_i32` has generic type parameters
   = note: method `get_u64` has generic type parameters
   = note: method `get_i64` has generic type parameters
   = note: method `get_uint` has generic type parameters
   = note: method `get_int` has generic type parameters
   = note: method `get_f32` has generic type parameters
   = note: method `get_f64` has generic type parameters
```

While I'm not sure if boxing buf is good for performance reasons, I'd prefer that boxing be allowed for flexibility.

This can be done in in two ways:
1. Use different methods `get_u16_le` and `get_u16_be`
2. Making a wrapper type: `buf.little_endian_reader().get_u16()`
While slightly less convenient, I still think it's beneficial to make a trait object-safe.

This can only be done as a breaking change in 0.5 though.

**Comment by carllerche** [comment]
One option is to add `where` clauses to all these fns, but then they would not be available as part of the trait object.

Adding `_be` and `_le` suffixes to the trait is the better option here.

**Comment by tailhook** [comment]
Is adding `where` clauses a backward-compatible change? I.e. can we add `where` clauses deprecate the methods and add new ones with suffixes?

**Comment by carllerche** [comment]
I... think? But @alexcrichton would know better.
