### ISSUE TITLE
Idea about new BytesPool type

### ISSUE THREAD

**Issue by Thomasdezeeuw** [carllerche/bytes#169]
I had an idea for a new `BytesPool` type that is a pool of buffers which will return them selves to the buffer once dropped. Basically it will a pool of buffer like any other, but it returns a wrapper type that once dropped will return the actual buffer to the pool. This allows for reusing buffers when you need to pass them to functions that don't take pooling into account. Some thing like this psuedo rust:

```rust
struct BytesPool;

impl {
    fn get(&self) -> BytesMut
    fn put(&self, BytesMut)
}

struct PooledBytesMut {
    pool: &BytesPool,
    inner: Option<BytesMut>,
}

Deref and Derefmut<BytesMut> for PooledBytesMut

impl Drop for PooledBytesMut {
    fn drop(&mut self) {
        let buf = self.inner.take();
        // Maybe only do it it's heap allocated.
        self.pool.put(buf);
    }
}
```

It's currently just an idea and it doesn't have to life in the bytes crate, maybe a seperate crate would be better. What do you think?

**Comment by carllerche** [comment]
A buffer pool is definitely useful. I do think it will require some experimentation that would be best done in a separate crate. Maybe you can try that and as things stabilize, we can see if it might fit in `bytes` proper.
