### ISSUE TITLE
Improve unsplit

### ISSUE THREAD

**Issue by carllerche** [carllerche/bytes#172]
A continuation of #162. Specifically:

There are actually a few further improvements that could be made [to unsplit]:

* Check if `other` is empty, in which case, no-op.
* Check if `self` is empty, in which case, just set `*self = other`.
* Use `extend_from_slice` instead of `extend` as it is more optimized for slices instead of iterators.

**Comment by jq-rs** [comment]
Worthy improvements, I'll take a look soon unless someone gets them in first.

**Comment by jq-rs** [comment]
Thanks for the merge! I tested the unsplit() version with my application and seems to function very well. If you could release a new bytes version to crates.io with unsplit() support, that would be just great. Thanks!

**Comment by carllerche** [comment]
Could you file an issue requesting a new release?

**Comment by carllerche** [comment]
Closed by #173
