### ISSUE TITLE
Optionally disable inlining

### ISSUE THREAD

**Issue by asomers** [carllerche/bytes#175]
Inlining a `Bytes` or `BytesMut` is undesirable when one needs to pass a raw pointer to an asynchronous C API.  If the `Bytes` is stack-allocated and inline, the location of the slice could change leaving the C library with a dangling pointer.  One solution to this problem is to always allocate your `Bytes` within a `Box`, but that leads to unnecessary malloc work.  A better solution would be to have a way to disable inline allocation.  I propose adding two methods to support this:

- `Bytes::is_inline`.  This method already exists, we would just need to make it public.
- `Bytes::with_capacity_stable`.  This would be like `with_capacity`, but it would guarantee stable storage.  An object initialized with this method would always return false for `is_inline`.

**Comment by mzabaluev** [comment]
I wonder if `Pin` can be used to deal with the problem now even in presence of the inline layout.
