### ISSUE TITLE
Update to use IoVec and IoVecMut instead of &IoVec and &mut IoVec

### ISSUE THREAD

**Issue by fryguy1013** [carllerche/bytes#177]
It seems like the API of IoVec will change, as seen in master with this changeset: https://github.com/carllerche/iovec/commit/db866454eb31b3dafe0308fff3e8551744f6c654

I've made a branch with a change to update the usage in this library, found here: https://github.com/fryguy1013/bytes/commit/55e8d2453a2dfa45de0404a674d3d42007afb1af

This is the first ever thing I've done in rust, but it compiles and all the tests pass which I'm told means it works. Feel free to use this patch when upgrading bytes to use the version of IoVec that uses the updated API.

**Comment by carllerche** [comment]
Thanks! That actually looks correct to me! I will pull it in.

**Comment by carllerche** [comment]
I pulled it in here: https://github.com/carllerche/bytes/pull/179
