### ISSUE TITLE
I don't understand the purpose of the library

### ISSUE THREAD

**Issue by dvtomas** [carllerche/bytes#181]
I feel stupid, but even after reading the docs several times with a few weeks between to digest it , I still don't understand the raison d’être of the crate.

I've used it it a couple of times to prepare a `Vec<u8>` packet with a couple of u16's, u32's etc to be later sent to some device, using it just as a sort of in-memory writer that takes care of advancing the pointer to Vec and handling endianness correctly. But I feel like I'm misusing the library. I don't understand when does the underlying storage grow automatically and when not and why. I don't understand the purpose of multiple handles to one underlying storage. The naming confuses me, starting with *"A utility library for working with bytes."* - does "working with bytes" really explain the purpose of the crate the best?

I don't want to be negative, I'm sure the crate is **very** useful for it's purpose and maybe even I need it today, but I just don't get it. I would really appreciate a typical scenario or two involving the core features of the crate playing together. Splitting "Hello, world" into two "`Bytes`" doesn't do that for me.

**Comment by hawkw** [comment]
A potentially relevant line from the documentation:
> `Bytes` values facilitate zero-copy network programming by allowing multiple `Bytes` objects to point to the same underlying memory. This is managed by using a reference count to track when the memory is no longer needed and can be freed.

**Comment by carllerche** [comment]
@dvtomas does the above snippet help clarify things? Do you understand the value of zero-copy network programming or is that where the disconnect lies?

**Comment by dvtomas** [comment]
Dear @hawkw ,
no, not really, I've read the above snippet before. I'll try to elaborate on what I fail to understand in more detail.

The snippet says that the crate helps us (allows us?) to do zero-copy network programming without further explaining WHAT exactly it enables me to do and HOW should I use it. I understand that perhaps each library user might have specific needs, but I still suspect that there are some typical exemplary usages of the library. Unfortunately, the documentation is totally silent on them, so from here on I can only guess :(

 1. I suspect that the library allows me to do zero-cost parsing of data that have arrived, is that correct? I currently use the library for something like that, but I'd be happy with just a buffer(&[u8]), sliding pointer to the buffer, and a bunch of get_i32<Endianness> and similar methods. Clearly the library offers much more (different implementations of buffer and the mythical "multiple bytes object pointing to the same memory"), so I'm missing something here.

2. I suspect that the library allows me to do zero cost generation of binary packets to be sent somewhere, is that correct? But again, most of the stuff from 1. applies here as well, in the end I need a &[u8] buffer of data to send (Writer.write()) somewhere. Right now I'm generating them with just buf.put_i32<Endianess> et al. methods. I'm even more lost here, because some underlying storages automatically grow and some not, and I totally don't understand which do, which not, when is it better to choose the auto-growing ones and when the static, and most importantly - WHY? What is the intuition behind some growing and some not? Another thing: I'm having trouble implementing the following scenario: I'm generating packets with this structure: `[Len Len Len Len MessageCode ..... Len bytes .... CSum CSum]`. I only know the len after generating the bytes, but in order to generate the binary representation with `Bytes` I need to fill it before generating the rest. Currently I do this by creating the underlying storage first, then converting it to Bytes, generate dummy zero Len bytes, then generate the data, convert it back to the storage (Vec<u8>) and ultimately modify the len bytes in the Vec inplace. Is this the idiomatic use of `Bytes` or should I use another approach, perhaps `Chain`ing the data or something? I dunno, there is no such recipe on this anywhere in the docs...

So, these are the two use cases I commonly deal with, and none of them involves "*multiple Bytes objects to point to the same underlying memory*", different types of underlying storage, growable/non-growable bufs or any other more fancy stuff the crate provides. I still have no idea at all on how these concepts are supposed to be used, how do they work together, and the docs don't help. I have a gut feeling that I'm missing something useful, I just don't know how to reach for it and what exactly to look for, and that's a little  frustrating. Perhaps the crate implements some design pattern I don't know and others do, so they immediately recognize it and just know how to use the crate and what to expect from it? I don't know, but if that is the case, please, at least point me to the relevant document. Maybe it's just that my use-cases aren't a good fit for the crate, or that they are perfectly happy with just a small subset of the crate. Even if that was the case, I'm still curious about the "grownup" uses of the crate.

Hope I've made myself more clear. Thank you for reading this.

**Comment by dvtomas** [comment]
After further thinking, I have to admit that I don't have experience with zero-copy network programming. If the case with `Bytes` is that it is not useful outside the zero-copy network programming domain, perhaps I'm barking at the wrong tree and just misusing the library, and people experienced with zero-copy network programming immediately recognize the patterns employed in the crate and feel comfortable understanding and using it. I can't tell for lack of knowledge. If that is indeed the case, I apologize for this issue.

**Comment by carllerche** [comment]
Working with `&[u8]` introduces lifetimes. `Bytes` uses reference counting. If working with slices is sufficient, then you should just use that.

Anyway, I don't really see any action items to take away from this issue. So, I will close it. Thanks for the report though.
