### ISSUE TITLE
Buf::copy_to_slice

### ISSUE THREAD

**Issue by tokengod** [carllerche/bytes#184]
214             unsafe {
215                 let src = self.bytes();
216                 cnt = cmp::min(src.len(), dst.len() - off);
217 
218                 ptr::copy_nonoverlapping(
219                     src.as_ptr(), dst[off..].as_mut_ptr(), cnt);
220 
221                 off += src.len();
222             }

In line 221,  should it be?
off += cnt;
I just couldn't understand the current logic, :(

ps, after i changed this line and all tests passed too

**Comment by carllerche** [comment]
You are correct. It should be `cnt`.

That said, even with the error, the logic is correct as `src.len() != cnt` implies this is the last iteration and using `src.len()` instead will result in the termination of the loop as well.

It is still worth fixing, but a least it isn't a safety hazard 😨

**Comment by carllerche** [comment]
This is fixed by ebe522731f6459ef7fb0e8900bfb2734f9fb14d4
