### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by nox** [carllerche/bytes#189]
We want to try and make use of `Bytes::to_mut` in some parts of Servo. I don't know if the other changes that landed since `0.5.0` are breaking or not, but you yourself probably know whether they are already. :)

**Comment by seanmonstar** [comment]
[0.5 isn't ready yet](https://github.com/carllerche/bytes/milestone/1), but if `to_mut` is a non-breaking change, it could be backported to the 0.4.x branch.

**Comment by carllerche** [comment]
Yeah, it would need to be back ported.

**Comment by carllerche** [comment]
@nox would you be able to backport? Otherwise, I probably won't get to it before next week.

**Comment by carllerche** [comment]
I'm going to close this as there has been no response.
