### ISSUE TITLE
Want a way to go from a &[u8] sub-slice to a Bytes

### ISSUE THREAD

**Issue by federicomenaquintero** [carllerche/bytes#198]
I'm using Bytes to hold data and then keep around slices from it.  The "main" data gets parsed with nom, which often returns `&[u8]` slices.  It would be convenient for my code to be able to go from those slices to `Bytes` slices on the original data:

```rust
pub trait Subslice {
    fn subslice(&self, sub: &[u8]) -> Self;
}

impl Subslice for Bytes {
    fn subslice(&self, sub: &[u8]) -> Bytes {
        let bytes_p = self.as_ptr() as usize;
        let bytes_len = self.len();

        let sub_p = sub.as_ptr() as usize;
        let sub_len = sub.len();

        assert!(sub_p >= bytes_p);
        assert!(sub_p + sub_len <= bytes_p + bytes_len);

        let sub_offset = sub_p - bytes_p;

        self.slice(sub_offset, sub_offset + sub_len)
    }
}
```

Do you think this should be in the Bytes API?  I already have tests for the above if you'd like a PR :smile:

**Comment by federicomenaquintero** [comment]
(To clarify: the `subslice` function would be in the `Bytes` impl, not in a separate trait.  I haven't thought about doing this on `BytesMut`.)

**Comment by carllerche** [comment]
Generally, I try to stay on the side of less APIs vs .more if it is possible to impl the fn outside of the library w/ no unsafe code. To include an API, it should be generally useful.

I think something like this might fit the criteria.

Of course, then we have to bikeshed the name :)

**Comment by federicomenaquintero** [comment]
`Bytes.slice_to_bytes`?  `Bytes.get_subslice`?  `Bytes.subslice`? :laughing:
