### ISSUE TITLE
`FromIterator<u8>` impl panics if `size_hint` is not available

### ISSUE THREAD

**Issue by stbuehler** [carllerche/bytes#199]
Test case:

```rust
use std::iter;
iter::repeat(b'x')
.scan(100, |cnt, item| if *cnt >= 1 { *cnt -= 1; Some(item) } else { None })
.collect::<bytes::Bytes>();
```

**Comment by carllerche** [comment]
Thanks for the report.

I accidentally pushed the fix directly to the `0.4.x` branch (I have not enable branch protection): https://github.com/carllerche/bytes/commit/b68fa46e3da7bff20f1be7850a4487131cb24a27
