### ISSUE TITLE
Release a new version of bytes

### ISSUE THREAD

**Issue by fhartwig** [carllerche/bytes#20]
Could you make a new bytes release and bump mio's bytes dependency? The buffers that mio re-exports still exhibit the bugs fixed in c4546493eaad57e69e37aa4205a08000bcf82153

**Comment by carllerche** [comment]
Done. Thanks.

Bytes: https://crates.io/crates/bytes/0.2.7
Mio: https://crates.io/crates/mio/0.3.3

**Comment by fhartwig** [comment]
Great, thank you! :smiley:
