### ISSUE TITLE
Endianness

### ISSUE THREAD

**Issue by samanpa** [carllerche/bytes#201]
I don't understand the reasoning for having different layout based on the endianness of the platform https://github.com/carllerche/bytes/blob/master/src/bytes.rs#L273-L282. Why can't big and little endian platforms share the same layout? Granted the the bytes in the arc field will be laid out differently based on the endianness.

**Comment by carllerche** [comment]
Because, for inline byte storage, it has to be continuous. To do this, the struct needs to be laid out differently based on endianness.

**Comment by samanpa** [comment]
Thanks, guess I should have read the part of the documentation that said that cap,ptr and len are used as part of the buff when in inline mode.
