### ISSUE TITLE
Include a Bytes-based ring buffer

### ISSUE THREAD

**Issue by djc** [carllerche/bytes#207]
I was thinking about my needs for a ring buffer-like data structure, and I think something like `Bytes` would be very useful. Would there be interest in including something like that in this crate?

I'm thinking it would be substantially similar to the current `Bytes`, except that something should keep track of which slices of the backing store still have non-zero reference counts. As soon as the reference count for a slice drops to zero, this is recorded, and there is some strategy for allocating newly free slices of the backing store again.

**Comment by gnzlbg** [comment]
[slice_deque](https://crates.io/crates/slice-deque) implements a ring-buffer that supports the Bytes API (need to enable the `bytes` cargo feature), [buf_redux](https://crates.io/crates/buf_redux) can be configured to use `slice_deque`.

**Comment by djc** [comment]
@gnzlbg that's very interesting! However, unless I'm mistaken it does not directly satisfy my idea about having allocated slices be reference-counted.

**Comment by carllerche** [comment]
What I would suggest is to start with an implementation out of crate and let it mature there. Then we can consider adding it. `bytes` needs to maintain a fairly high level of stability.

That said, I'm also considering a facade approach (similar to tokio) for the next breaking release. This would enable iterating faster.

**Comment by djc** [comment]
Fair enough, I'll close this for now.

**Comment by dignifiedquire** [comment]
did anything come out of this? I am looking for a solution to this exact problem as well

**Comment by Darksonn** [comment]
No, it's probably not going to happen in the bytes crate.

**Comment by dignifiedquire** [comment]
> probably not going to happen in the bytes crate

makes sense, I was just hoping someone had maybe written sth like this 😅
