### ISSUE TITLE
Using Buf::bytes() and advance() together is not possible

### ISSUE THREAD

**Issue by sunshowers** [carllerche/bytes#213]
Since `advance()` does a mutable borrow, there's no way to call it while holding onto bytestrings returned from `bytes()`. This is useful when e.g. collecting ranges of bytes in a vector that will be joined together in the end.

This is an operation that should be logically possible, but the Rust type system and the `Buf` interface make it not so.

Ideally I'd be the one tracking the offset within `advance()`, not the buffer itself -- or maybe I'd have a way to get hold of later slices of data without calling `advance()`.

**Comment by carllerche** [comment]
This is intended. You would copy the data out then call `advance`. Do you have more context as to why you want to call `advance` while holding a reference to the data?

**Comment by sunshowers** [comment]
I'd like to stash a bunch of slices chosen from a `Buf` in a `Vec<&[u8]>` and then join them together at the end.

**Comment by carllerche** [comment]
You can get multiple slices at a time using `bytes_vec`: https://docs.rs/bytes/0.4.8/bytes/trait.Buf.html#method.bytes_vec

But, short of that, you will need to copy.

I'm going to close the issue, but feel free to continue commenting if you have additional questions.
