### ISSUE TITLE
Why is Result not utilized?

### ISSUE THREAD

**Issue by Redrield** [carllerche/bytes#222]
Why is it that get_* functions in `Buf` panic if there is no more data remaining, rather than returning an error? I wrote an extension trait for this that didn't take much time but it confuses me why it's preferable for a bad read to bring down its thread rather than allowing the user to handle it gracefully.

**Comment by carllerche** [comment]
Because `Result` is intended to represent runtime errors that can happen in bug free code. Panics are used to represent errors due to bugs.

**Comment by carllerche** [comment]
Do you disagree with the guideline?

**Comment by Redrield** [comment]
I find that using Result would be a lot less opinionated about how errors should be managed, because it gives the option for graceful handling while also allowing a panic if you're sure it's acting as it's supposed to
