### ISSUE TITLE
Clarify branch usage in that repository

### ISSUE THREAD

**Issue by nox** [carllerche/bytes#237]
I added `Bytes::to_mut` in #188 but I couldn't find it in the code or the docs. Then I realised it was merged against the `master` branch, which is not the main branch in that repository, and which is older than the `v0.4.x` branch. Which is the canonical one? Is the master one still relevant? When will `to_mut` ever be in a published version?

**Comment by carllerche** [comment]
Sorry for the delay, I've been on vacation :)

I would focus on 0.4.x. The other branch has stalled until a point where the Tokio ecosystem issues a large breaking change. At that point, I will ensure all 0.4.x work has been forwards ported to master.

I would take a PR that back ports #188 to 0.4.x.

Does this answer your question?
