### ISSUE TITLE
Need method to mutably access already written parts of MutByteBuf

### ISSUE THREAD

**Issue by sdroege** [carllerche/bytes#24]
It would be convenient to have something like MutByteBuf::mut_bytes() that gives access to the already written part of the byte buffer instead of the remaining memory area. This would allow to modify something that was received from the network, and potentially forwarding it to some other socket, without having to copy everything.

**Comment by carllerche** [comment]
Definitely an interesting thought. The use case that you have should definitely be supported. I've been mulling around some other use cases recently and will see if I can try to combine all of them and write up some new APIs to handle them... though, my initial thought is a `MutByteBuf::mut_bytes()` API is correct.

**Comment by sdroege** [comment]
FWIW, code where this would be useful is here: https://github.com/sdroege/ptp-clock-reflector/blob/master/src/main.rs

Ideally I'd like to allocate the buffer only once and store it inside the struct in an Option<>, take() it from there in the beginning of readable(), receive/mutate/send, flip it back to a mutable, empty buffer and store it inside the struct again

**Comment by carllerche** [comment]
I would take a `MutByteBuf::mut_bytes()` PR :)

**Comment by carllerche** [comment]
Handled w/ refactor
