### ISSUE TITLE
Feature request: `Bytes::unadvance` to undo `advance`.

### ISSUE THREAD

**Issue by vi** [carllerche/bytes#245]
`pub fn unadvance (&mut self, cnt: usize) -> Option<()>`

The function may refuse to work (`Option<()>`) or just copy data if needed (`()`).

The idea is to make a `Bytes` instance with some data and a reserved space for a header, process that byte buffer though some external library, then prepend header without copying data around and send it somewhere without sendmsg, with regular means instead.

1. Allocate a buffer
2. Advance it e.g. 28 bytes ahead
3. Write some data into it
4. Give the buffer to a library, which processes and mutates visible data in the buffer
5. Take the buffer back from the library
6. Unadvance it from 28-byte offset back to 0-offset.
7. Write headers
8. Send.

Like reserved capacity, but at the beginning instead of at the end of the buffer.

**Comment by chpio** [comment]
or something like [unsplit](https://docs.rs/bytes/0.4.11/bytes/struct.BytesMut.html#method.unsplit) + `split_off_mut` for "`mut`"/write-buffer.

```rust
let mut buf = BytesMut::with_capacity(64);

let body = buf.split_off_mut(6);

// buf is the head
buf.put_u8(42);

buf.unsplit(body);
// should "just" work, eg. if "head"/buf has free memory left it would `buf.extend_from_slice(body)`
```

**Comment by carllerche** [comment]
If you are working directly with `Bytes`, it does seem like using `split_off` is the best way here.

If you are concerned with the ref count increase, there may be other ways of working it as well.

**Comment by chpio** [comment]
> If you are working directly with `Bytes`, it does seem like using `split_off` is the best way here.

There is no `split_off` for `BytesMut` (he's trying to write to a buffer, so i guess he actually wants a `BytesMut`).

**Comment by carllerche** [comment]
@chpio sure, makes sense.

I'm going to close this issue as a path forward has been suggested that works without changes to `bytes`. @vi If this path is insufficient, please comment and I can open it again.
