### ISSUE TITLE
Buf (and BufMut) for VecDeque

### ISSUE THREAD

**Issue by vorner** [carllerche/bytes#248]
Hello

I'd like to have an idea validated before I jump in and implement it.

Let's say I have a decoding routine for a record and it requires `IntoBuf`. I don't know how large the record is going to be ahead of decoding it, but either there's an upper limit or it's able to tell me „not enough, give me more“. I have a huge file of these records (specifically, these are length-prefixed protobuf encoded messages and I want to use prost to decode it).

I could just slurp the whole file into memory and then repeatedly try to decode the message, like this:

```rust
let mut buffer = Vec::new();
file.read_to_end(&mut buffer)?;
let mut buffer = Cursor::new(buffer);
while buffer.position() < buffer.len() as usize {
  let _msg = Message::decode_length_delimited(&mut buffer)?;
}
```

This, however, has the downside of putting the whole huge file into RAM.

I'd like something more in the lines of:

```rust
let mut buffer = SomeBuffer::new();
while !buffer.is_empty() {
    // If there's less than LOW_MARK, tries to read enough to reach HIGH_MARK.
    // It's outside of the `Buf` trait methods, because this can return errors.
    // Stores an eof mark if it reaches end of the file and is_empty will return true only
    // if it contains no bytes and eof was reached.
    buffer.refill(HIGH_MARK, LOW_MARK, &mut file)?;
    let _msg = Message::decode_length_delimited(&mut buffer)?;
}
```

Now, this is somewhat higher level API, but I was wondering how to implement it. My first thought would be `BytesMut` should be able to do it (even after reading code related to tokio::codec and tokio::io suggest it should be the way forward). However, I don't see one thing. The `BytesMut` tries to have everything in a continuous chunk of memory. So, if I have the bad luck of never consuming the full buffer and leaving something in there every time, an unused space on the left will gradually grow while I'll keep allocating on the right. Or how does this work? If it does work by some trick I don't see, is it possible to extend the documentation with an example and explanation?

However, then I discovered that what I need is mostly a FIFO for bytes and that's what VecDeque does. I believe implementing `Buf` for it should be easy. Regarding this, do you see any problem with having VecDeque implement it? Does it make sense? If so, I'll send a PR.

**Comment by carllerche** [comment]
Yep. I think that you are on the right path. The crate used to contain a RingBuf type that had a fixed capacity. I think your best bet would be to define a type and wrap VecDeque.

You can look at the old RingBuf for inspiration. https://github.com/carllerche/bytes-more/blob/master/src/ring.rs

**Comment by carllerche** [comment]
I’m going to close the issue as there is no further action for the crate. Feel free to reply though as I get notified.

**Comment by vorner** [comment]
Actually, I was thinking about putting the implementation into the crate without the wrapper. I believe the implementation would be very simple.

**Comment by carllerche** [comment]
My current inclination is to try to avoid adding more things to the `bytes` crate. It is mostly a question of maintenance burden. If it lives in this crates, updating it because a blocker for releasing `bytes` 0.5 (and I am currently pretty overloaded in terms of maintenance).
