### ISSUE TITLE
BytesMut::split_to doesn't panic as it should

### ISSUE THREAD

**Issue by Riateche** [carllerche/bytes#252]
The method's documentation says "Panics if `at > len`". But this test fails (the code doesn't panic):
```
#[test]
#[should_panic]
fn test_split_to() {
    let mut buf = BytesMut::from(&b"hello world"[..]);
    let len = buf.len();
    let x = buf.split_to(len + 1);
}
```
Unlike `Bytes::split_to`, `BytesMut::split_to` doesn't have an assert that enforces `at <= len`. There is even a test (`split_to_uninitialized`) that checks for the lack of the assert.

Is this a documentation issue or should the implementation (and tests) be fixed? Why are `Bytes` and `BytesMut` inconsistent?

**Comment by carllerche** [comment]
ah... it probably should panic.. I'm not sure why the test checks that it doesn't... I would love a PR ❤️
