### ISSUE TITLE
Implement RingBuf reserve() or grow() function

### ISSUE THREAD

**Issue by jnicholls** [carllerche/bytes#29]
It would be nice to be able to do a realloc on the RingBuf to grow it in size.  A deep copy is necessary today to accomplish this.

p.s. I might just submit a PR :)

**Comment by carllerche** [comment]
:+1: definitely

**Comment by carllerche** [comment]
Same w/ bytebuf as well

**Comment by carllerche** [comment]
RingBuf has been moved to bytes-more. I'm going to close this issue for now.
