### ISSUE TITLE
Docs don't include public structures

### ISSUE THREAD

**Issue by geofft** [carllerche/bytes#41]
For instance, `ByteBuf` certainly looks like it's trying to be publicly documented, but it's not showing up in the rustdoc. All you see is a list of re-exports from private modules.

**Comment by fhartwig** [comment]
That's a bug in rustdoc. @carllerche has filed [an issue](https://github.com/rust-lang/rust/issues/24296). I've been meaning to look into this, but I haven't gotten around to it yet.
If you need a workaround, you can make the `buf` and `str` modules public and then build the docs locally.

**Comment by carllerche** [comment]
I worked around by making `buf` and `str` public since it doesn't seem like the issue is getting any love :(

**Comment by fhartwig** [comment]
The rustdoc bugs seems to have been fixed. If I make `buf` and `str` private and build the docs with the current nightly, all the structs are included in the docs.

**Comment by carllerche** [comment]
Hmm... I don't actually dislike keeping the modules public now. I may remove the root re-exports. Unsure.
