### ISSUE TITLE
ReadExt.read_buf doesn't distinguish between read returning 0 and a full buffer

### ISSUE THREAD

**Issue by ousado** [carllerche/bytes#49]
In both cases Ok(0) is returned, making it impossible to distinguish between a closed connection and a full buffer ( !buf.has_remaining() )
https://github.com/carllerche/bytes/blob/f693e038d9ad3042c0a68bb3ef609117b1d7a86a/src/buf/mod.rs#L439

**Comment by carllerche** [comment]
Hey, thanks for the report. The current behavior matches the behavior of the `read` syscall. If you pass a zero length buffer to `read` it returns `Ok(0)`. One should always check if the buffer has remaining capacity before passing it to read again.

I'm going to close this for now, but if you disagree, I would be interested in hearing more about why you think it should have different behavior than `read()` and what you think it should do.
