### ISSUE TITLE
ReadExt may not be safe

### ISSUE THREAD

**Issue by alexcrichton** [carllerche/bytes#51]
The [current implementation](https://github.com/carllerche/bytes/blob/4ca7e0fabf3717a033bb57698164caa0f84bb79f/src/imp/buf/mod.rs#L537-L555) exposes uninitialized memory via `mut_bytes` to arbitrary implementors of the `Read` trait. Unfortunately though arbitrary implementors don't guarantee that they won't read the uninitialized data.

**Comment by carllerche** [comment]
Sigh... sounds about right. This could be implemented directly on types then... the std::io traits should probably have a way to read into uninitialized bytes.

**Comment by carllerche** [comment]
Thinking more about this, it sounds like a general problem of never being able to use uninitialized bytes, which is a pretty heavy requirement

**Comment by alexcrichton** [comment]
Yeah I think a solution to this would likely be best done through `std::io::Read` actually. There's already an optimization like this for `read_to_end` which some types implement but not all. 

I'm thinking we could do something like:

```rust
trait Read {
    // ...
    unsafe fn read_uninitialized(&mut self, buf: &mut [u8]) -> io::Result<usize> {
        for slot in buf {
            *slot = 0;
        }
        self.read(buf)
    }
}
```

**Comment by carllerche** [comment]
This has been removed from the lib
