### ISSUE TITLE
Provide support for a &'static [u8] in Bytes

### ISSUE THREAD

**Issue by seanmonstar** [carllerche/bytes#57]
It'd be nice if `Bytes::from(b"foo bar")` would just grab the static pointer, and not copy the bytes.

This would probably requiring changing the representation slightly of `Bytes` since it couldn't be a `BytesMut` of a static memory pointer. Additionally, the `try_mut` and `into_mut` methods would not be allowed to return a `BytesMut` in that case. Would be very useful for https://github.com/hyperium/hyper/issues/953

**Comment by carllerche** [comment]
This is on master.
