### ISSUE TITLE
Consider reducing the struct size

### ISSUE THREAD

**Issue by arthurprs** [carllerche/bytes#59]
Great work on the library, super useful. I was wondering if you would consider reducing the Buffer struct to 24bytes (64bits) (by using 32bit len/cap or something else)?

This will reduce the inline capacity but 23 is still plenty in practice. Even if moving single Buffers around is essentially the same speed (2x128bit moves vs 1x128 and 1x64bit) it really helps when you have more than a single buffer in a struct, enum, array, etc..

**Comment by carllerche** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
I talked with @carllerche a bit on IRC about this, the conclusion was that the current layout of the struct is required to support >4GB buffers in all the various situations it's intended to be used in. In that sense I couldn't think of a way to optimize the struct representation *without* compromising on some usability aspect of the API.

In that sense I think our only option here is to have an API tradeoff:

* Don't support >4GB buffers
* Don't support multiple `BytesMut` windows into the same backing store

(I think that was it)

Without compelling data I'd personally be wary of changing the struct representation to add a limitation. I would, however, be totally on board with changing the representation to support all the existing use cases if possible!

**Comment by arthurprs** [comment]
I can't really talk about the second point, but is supporting 4GB+ buffers really important?

**Comment by alexcrichton** [comment]
Due to how general this crate is targeted to be I'd think that the use case of worrying about struct size isn't any less niche than the use case requiring >4GB buffers.

**Comment by arthurprs** [comment]
That's fair.
