### ISSUE TITLE
Doesn’t compile on 32 bit platforms

### ISSUE THREAD

**Issue by nwin** [carllerche/bytes#6]
It doesn’t compile on 32 bit platforms.

    src/alloc.rs:5:32: 5:39 error: bitshift exceeds the type's number of bits, #[deny(exceeding_bitshifts)] on by default
    src/alloc.rs:5 const MAX_ALLOC_SIZE: usize = (1 << 32) - 1;
                                                  ^~~~~~~

**Comment by carllerche** [comment]
This should be fixed on master! Thanks.
