### ISSUE TITLE
Define API behavior

### ISSUE THREAD

**Issue by carllerche** [carllerche/bytes#69]
* What does `bytes_vec` do when remaining == 0

Probably guaranteed to return `0`.

* Can the argument to `bytes_vec` be an empty slice?

Yes

* Buf::advance past `remaining`

Maybe panic?

**Comment by alexcrichton** [comment]
* "Fusing behavior". That is, if you advance to the end, then keep poking (e.g. advancing, `bytes`, `bytes_vec`, etc) is it guaranteed to stay empty?

(I'd say yes)
