### ISSUE TITLE
Bytes::concat(Bytes, Bytes)

### ISSUE THREAD

**Issue by stepancheg** [carllerche/bytes#85]
Implement `Bytes::concat(Bytes, Bytes)`.

It can do two optimizations beyond just allocating a new buffer and copying data there:

* if either parameter is empty, return the other one
* if either parameter is "mut safe" and have enough capacity, copy the other one to it (this one is not possible to do from the outside of bytes crate)
* otherwise allocate a new buf and copy both parameters to it

**Comment by carllerche** [comment]
I think that something like this would be good. It could probably go as a `&mut self` fn on both `Bytes` and `BytesMut` though.

**Comment by carllerche** [comment]
I believe that this is related to #109
