### ISSUE TITLE
Index/indexMut instead of slice function

### ISSUE THREAD

**Issue by est31** [carllerche/bytes#98]
It would be really cool if you could just use slicing syntax on a Buf and get a Buf again, like `let b: Bytes = Bytes::from(&b"12323456"[..])[0..2];`. That can be done via implementing the Index/IndexMut trait for ranges.

Right now you have the slice function, that's quite ugly.

**Comment by carllerche** [comment]
Unfortunately, this is not possible as `Index` / `IndexMut` requires returning a ref. At some point in the future, there may be an index move trait, but until there is, we are stuck w/ the split fns.

**Comment by est31** [comment]
I see. Its a bit sad though.
