### ISSUE TITLE
Ability to opt out of thread safety

### ISSUE THREAD

**Issue by est31** [carllerche/bytes#99]
Apparently right now you need to use the internal `AtomicPtr` even though the implementation might never see multiple threads. You should be able to statically opt out of thread safety somehow.

**Comment by carllerche** [comment]
Could you elaborate on the perceived downside of using the `AtomicPtr`?

**Comment by est31** [comment]
@carllerche atomic primitives have a very low overhead compared to say locks or mutexes, but there is still one.

**Comment by carllerche** [comment]
Do you have any benchmarks of a real use case in which the `AtomicPtr` use is noticeable? This would help prioritize the request.

**Comment by carllerche** [comment]
Also, it would be helpful to be a bit less vague than "but there is still one". What specific overhead are you concerned about?

**Comment by est31** [comment]
Hmm seems according to this answer there should be no overhead: http://stackoverflow.com/a/38465341

after all rust does alignment.
